// OUI (Organizationally Unique Identifier) Lookup
// Maps MAC address prefixes to vendor names

interface OUIEntry {
  prefix: string
  vendor: string
}

// Common vendor OUI prefixes (first 3 octets of MAC address)
const OUI_DATABASE: OUIEntry[] = [
  { prefix: '00:00:0C', vendor: 'Cisco' },
  { prefix: '00:1B:63', vendor: 'Apple' },
  { prefix: '00:1C:B3', vendor: 'Apple' },
  { prefix: '00:1E:C2', vendor: 'Apple' },
  { prefix: '00:1F:5B', vendor: 'Apple' },
  { prefix: '00:1F:F3', vendor: 'Apple' },
  { prefix: '00:21:E9', vendor: 'Apple' },
  { prefix: '00:22:41', vendor: 'Apple' },
  { prefix: '00:23:12', vendor: 'Apple' },
  { prefix: '00:23:32', vendor: 'Apple' },
  { prefix: '00:23:6C', vendor: 'Apple' },
  { prefix: '00:23:DF', vendor: 'Apple' },
  { prefix: '00:24:36', vendor: 'Apple' },
  { prefix: '00:25:00', vendor: 'Apple' },
  { prefix: '00:25:4B', vendor: 'Apple' },
  { prefix: '00:25:BC', vendor: 'Apple' },
  { prefix: '00:26:08', vendor: 'Apple' },
  { prefix: '00:26:4A', vendor: 'Apple' },
  { prefix: '00:26:B0', vendor: 'Apple' },
  { prefix: '00:26:BB', vendor: 'Apple' },
  { prefix: '04:0C:CE', vendor: 'Apple' },
  { prefix: '04:15:52', vendor: 'Apple' },
  { prefix: '04:26:65', vendor: 'Apple' },
  { prefix: '04:48:9A', vendor: 'Apple' },
  { prefix: '04:54:53', vendor: 'Apple' },
  { prefix: '04:69:F8', vendor: 'Apple' },
  { prefix: '04:D3:CF', vendor: 'Apple' },
  { prefix: '04:DB:56', vendor: 'Apple' },
  { prefix: '04:E5:36', vendor: 'Apple' },
  { prefix: '04:F1:3E', vendor: 'Apple' },
  { prefix: '04:F7:E4', vendor: 'Apple' },
  { prefix: '08:00:07', vendor: 'Apple' },
  { prefix: '08:66:98', vendor: 'Apple' },
  { prefix: '08:70:45', vendor: 'Apple' },
  { prefix: '08:F4:AB', vendor: 'Apple' },
  { prefix: '0C:3E:9F', vendor: 'Apple' },
  { prefix: '0C:4D:E9', vendor: 'Apple' },
  { prefix: '0C:74:C2', vendor: 'Apple' },
  { prefix: '10:40:F3', vendor: 'Apple' },
  { prefix: '10:41:7F', vendor: 'Apple' },
  { prefix: '10:9A:DD', vendor: 'Apple' },
  { prefix: '10:DD:B1', vendor: 'Apple' },
  { prefix: '14:10:9F', vendor: 'Apple' },
  { prefix: '14:5A:05', vendor: 'Apple' },
  { prefix: '14:8F:C6', vendor: 'Apple' },
  // Samsung
  { prefix: '00:12:47', vendor: 'Samsung' },
  { prefix: '00:12:FB', vendor: 'Samsung' },
  { prefix: '34:AA:8B', vendor: 'Samsung' },
  { prefix: '38:0A:94', vendor: 'Samsung' },
  { prefix: '3C:5A:37', vendor: 'Samsung' },
  { prefix: '40:0E:85', vendor: 'Samsung' },
  { prefix: '44:4E:6D', vendor: 'Samsung' },
  { prefix: '48:5A:3F', vendor: 'Samsung' },
  { prefix: '4C:BC:A5', vendor: 'Samsung' },
  { prefix: '50:32:37', vendor: 'Samsung' },
  { prefix: '50:B7:C3', vendor: 'Samsung' },
  { prefix: '54:88:0E', vendor: 'Samsung' },
  { prefix: '58:A2:B5', vendor: 'Samsung' },
  { prefix: '5C:0A:5B', vendor: 'Samsung' },
  { prefix: '60:6B:BD', vendor: 'Samsung' },
  { prefix: '64:B8:53', vendor: 'Samsung' },
  { prefix: '68:EB:AE', vendor: 'Samsung' },
  { prefix: '6C:2F:2C', vendor: 'Samsung' },
  { prefix: '70:F9:27', vendor: 'Samsung' },
  { prefix: '74:45:8A', vendor: 'Samsung' },
  { prefix: '78:1F:DB', vendor: 'Samsung' },
  { prefix: '7C:61:66', vendor: 'Samsung' },
  { prefix: '80:57:19', vendor: 'Samsung' },
  { prefix: '84:25:DB', vendor: 'Samsung' },
  { prefix: '88:32:9B', vendor: 'Samsung' },
  { prefix: '8C:77:12', vendor: 'Samsung' },
  { prefix: '90:18:7C', vendor: 'Samsung' },
  { prefix: '94:35:0A', vendor: 'Samsung' },
  { prefix: '98:52:B1', vendor: 'Samsung' },
  { prefix: '9C:02:98', vendor: 'Samsung' },
  { prefix: 'A0:07:98', vendor: 'Samsung' },
  { prefix: 'A0:21:95', vendor: 'Samsung' },
  { prefix: 'A4:EB:D3', vendor: 'Samsung' },
  { prefix: 'A8:F2:74', vendor: 'Samsung' },
  { prefix: 'AC:36:13', vendor: 'Samsung' },
  { prefix: 'B0:C5:59', vendor: 'Samsung' },
  { prefix: 'B4:07:F9', vendor: 'Samsung' },
  { prefix: 'B8:5E:7B', vendor: 'Samsung' },
  { prefix: 'BC:20:BA', vendor: 'Samsung' },
  { prefix: 'BC:72:B1', vendor: 'Samsung' },
  { prefix: 'C0:BD:D1', vendor: 'Samsung' },
  { prefix: 'C4:42:02', vendor: 'Samsung' },
  { prefix: 'C4:57:6E', vendor: 'Samsung' },
  { prefix: 'C8:19:F7', vendor: 'Samsung' },
  { prefix: 'CC:07:AB', vendor: 'Samsung' },
  { prefix: 'CC:3A:61', vendor: 'Samsung' },
  { prefix: 'D0:17:6A', vendor: 'Samsung' },
  { prefix: 'D0:22:BE', vendor: 'Samsung' },
  { prefix: 'D0:59:E4', vendor: 'Samsung' },
  { prefix: 'D4:87:D8', vendor: 'Samsung' },
  { prefix: 'D4:E8:B2', vendor: 'Samsung' },
  { prefix: 'D8:57:EF', vendor: 'Samsung' },
  { prefix: 'DC:71:44', vendor: 'Samsung' },
  { prefix: 'E4:12:1D', vendor: 'Samsung' },
  { prefix: 'E4:40:E2', vendor: 'Samsung' },
  { prefix: 'E8:03:9A', vendor: 'Samsung' },
  { prefix: 'E8:50:8B', vendor: 'Samsung' },
  { prefix: 'EC:1D:8B', vendor: 'Samsung' },
  { prefix: 'F0:08:F1', vendor: 'Samsung' },
  { prefix: 'F0:25:B7', vendor: 'Samsung' },
  { prefix: 'F4:09:D8', vendor: 'Samsung' },
  { prefix: 'F4:7B:5E', vendor: 'Samsung' },
  { prefix: 'F8:04:2E', vendor: 'Samsung' },
  { prefix: 'F8:D0:BD', vendor: 'Samsung' },
  { prefix: 'FC:03:9F', vendor: 'Samsung' },
  // Google
  { prefix: '00:1A:11', vendor: 'Google' },
  { prefix: '3C:5A:B4', vendor: 'Google' },
  { prefix: '54:60:09', vendor: 'Google' },
  { prefix: '6C:AD:F8', vendor: 'Google' },
  { prefix: '74:E5:43', vendor: 'Google' },
  { prefix: '84:1B:5E', vendor: 'Google' },
  { prefix: 'A4:77:33', vendor: 'Google' },
  { prefix: 'B4:F6:1C', vendor: 'Google' },
  { prefix: 'CC:3D:82', vendor: 'Google' },
  { prefix: 'D8:0D:17', vendor: 'Google' },
  { prefix: 'F4:F5:D8', vendor: 'Google' },
  { prefix: 'F8:8F:CA', vendor: 'Google' },
  // TP-Link
  { prefix: '00:27:19', vendor: 'TP-Link' },
  { prefix: '14:CF:92', vendor: 'TP-Link' },
  { prefix: '18:D6:C7', vendor: 'TP-Link' },
  { prefix: '1C:3B:F3', vendor: 'TP-Link' },
  { prefix: '30:B5:C2', vendor: 'TP-Link' },
  { prefix: '50:C7:BF', vendor: 'TP-Link' },
  { prefix: '54:AF:97', vendor: 'TP-Link' },
  { prefix: '60:E3:27', vendor: 'TP-Link' },
  { prefix: '74:DA:88', vendor: 'TP-Link' },
  { prefix: '84:16:F9', vendor: 'TP-Link' },
  { prefix: '98:DA:C4', vendor: 'TP-Link' },
  { prefix: 'A0:F3:C1', vendor: 'TP-Link' },
  { prefix: 'A4:2B:B0', vendor: 'TP-Link' },
  { prefix: 'B0:4E:26', vendor: 'TP-Link' },
  { prefix: 'B0:95:75', vendor: 'TP-Link' },
  { prefix: 'C0:25:E9', vendor: 'TP-Link' },
  { prefix: 'C4:6E:1F', vendor: 'TP-Link' },
  { prefix: 'D8:07:B6', vendor: 'TP-Link' },
  { prefix: 'E8:48:B8', vendor: 'TP-Link' },
  { prefix: 'EC:08:6B', vendor: 'TP-Link' },
  { prefix: 'F4:EC:38', vendor: 'TP-Link' },
  { prefix: 'F8:E4:3B', vendor: 'TP-Link' },
  // Xiaomi
  { prefix: '00:9E:C8', vendor: 'Xiaomi' },
  { prefix: '04:CF:4B', vendor: 'Xiaomi' },
  { prefix: '28:6C:07', vendor: 'Xiaomi' },
  { prefix: '34:CE:00', vendor: 'Xiaomi' },
  { prefix: '50:8F:4C', vendor: 'Xiaomi' },
  { prefix: '64:09:80', vendor: 'Xiaomi' },
  { prefix: '64:B4:73', vendor: 'Xiaomi' },
  { prefix: '68:DF:DD', vendor: 'Xiaomi' },
  { prefix: '78:02:F8', vendor: 'Xiaomi' },
  { prefix: '78:11:DC', vendor: 'Xiaomi' },
  { prefix: '8C:BE:BE', vendor: 'Xiaomi' },
  { prefix: '98:FA:E3', vendor: 'Xiaomi' },
  { prefix: 'A0:86:C6', vendor: 'Xiaomi' },
  { prefix: 'AC:23:3F', vendor: 'Xiaomi' },
  { prefix: 'C4:0B:CB', vendor: 'Xiaomi' },
  { prefix: 'F0:B4:29', vendor: 'Xiaomi' },
  { prefix: 'F4:8E:92', vendor: 'Xiaomi' },
  { prefix: 'FC:64:BA', vendor: 'Xiaomi' },
  // Huawei
  { prefix: '00:18:82', vendor: 'Huawei' },
  { prefix: '00:1E:10', vendor: 'Huawei' },
  { prefix: '00:25:9E', vendor: 'Huawei' },
  { prefix: '00:46:4B', vendor: 'Huawei' },
  { prefix: '00:66:4B', vendor: 'Huawei' },
  { prefix: '00:E0:FC', vendor: 'Huawei' },
  { prefix: '04:02:1F', vendor: 'Huawei' },
  { prefix: '08:7A:4C', vendor: 'Huawei' },
  { prefix: '0C:37:DC', vendor: 'Huawei' },
  { prefix: '10:C6:1F', vendor: 'Huawei' },
  { prefix: '18:4F:32', vendor: 'Huawei' },
  { prefix: '1C:1D:67', vendor: 'Huawei' },
  { prefix: '20:F3:A3', vendor: 'Huawei' },
  { prefix: '24:09:95', vendor: 'Huawei' },
  { prefix: '28:31:52', vendor: 'Huawei' },
]

export function lookupVendor(macAddress: string): string | undefined {
  if (!macAddress) return undefined
  
  // Normalize MAC address (remove separators, uppercase)
  const normalized = macAddress.replace(/[:-]/g, '').toUpperCase()
  if (normalized.length < 6) return undefined
  
  // Get first 3 octets (6 hex chars)
  const prefix = normalized.slice(0, 6)
  
  // Format as XX:XX:XX
  const formattedPrefix = `${prefix.slice(0, 2)}:${prefix.slice(2, 4)}:${prefix.slice(4, 6)}`
  
  // Lookup in database
  const entry = OUI_DATABASE.find(e => e.prefix === formattedPrefix)
  return entry?.vendor
}
