package defpackage;

/* compiled from: r8-map-id-6c2465e8d13ff8e5d50a476d17d9ba5832a97d3f7cd313d64bb1ddbb52494e1b */
/* loaded from: classes.dex */
public abstract class f81 {
    public static final a5 a;
    public static final a5 b;
    public static final a5 c;
    public static final a5 d;
    public static final a5 e;
    public static final e81 f;
    public static final a5 g;

    static {
        new a5(0, "VISUAL_STATE_CALLBACK", "VISUAL_STATE_CALLBACK");
        new a5(0, "OFF_SCREEN_PRERASTER", "OFF_SCREEN_PRERASTER");
        new a5(3, "SAFE_BROWSING_ENABLE", "SAFE_BROWSING_ENABLE");
        new a5(1, "DISABLED_ACTION_MODE_MENU_ITEMS", "DISABLED_ACTION_MODE_MENU_ITEMS");
        new a5(4, "START_SAFE_BROWSING", "START_SAFE_BROWSING");
        new a5(4, "SAFE_BROWSING_WHITELIST", "SAFE_BROWSING_WHITELIST");
        new a5(4, "SAFE_BROWSING_WHITELIST", "SAFE_BROWSING_ALLOWLIST");
        new a5(4, "SAFE_BROWSING_ALLOWLIST", "SAFE_BROWSING_WHITELIST");
        new a5(4, "SAFE_BROWSING_ALLOWLIST", "SAFE_BROWSING_ALLOWLIST");
        new a5(4, "SAFE_BROWSING_PRIVACY_POLICY_URL", "SAFE_BROWSING_PRIVACY_POLICY_URL");
        new a5(1, "SERVICE_WORKER_BASIC_USAGE", "SERVICE_WORKER_BASIC_USAGE");
        new a5(1, "SERVICE_WORKER_CACHE_MODE", "SERVICE_WORKER_CACHE_MODE");
        new a5(1, "SERVICE_WORKER_CONTENT_ACCESS", "SERVICE_WORKER_CONTENT_ACCESS");
        new a5(1, "SERVICE_WORKER_FILE_ACCESS", "SERVICE_WORKER_FILE_ACCESS");
        new a5(1, "SERVICE_WORKER_BLOCK_NETWORK_LOADS", "SERVICE_WORKER_BLOCK_NETWORK_LOADS");
        new a5(1, "SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST", "SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST");
        new a5(0, "RECEIVE_WEB_RESOURCE_ERROR", "RECEIVE_WEB_RESOURCE_ERROR");
        new a5(0, "RECEIVE_HTTP_ERROR", "RECEIVE_HTTP_ERROR");
        new a5(1, "SHOULD_OVERRIDE_WITH_REDIRECTS", "SHOULD_OVERRIDE_WITH_REDIRECTS");
        new a5(4, "SAFE_BROWSING_HIT", "SAFE_BROWSING_HIT");
        new a5(1, "WEB_RESOURCE_REQUEST_IS_REDIRECT", "WEB_RESOURCE_REQUEST_IS_REDIRECT");
        new a5(0, "WEB_RESOURCE_ERROR_GET_DESCRIPTION", "WEB_RESOURCE_ERROR_GET_DESCRIPTION");
        new a5(0, "WEB_RESOURCE_ERROR_GET_CODE", "WEB_RESOURCE_ERROR_GET_CODE");
        new a5(4, "SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY", "SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY");
        new a5(4, "SAFE_BROWSING_RESPONSE_PROCEED", "SAFE_BROWSING_RESPONSE_PROCEED");
        new a5(4, "SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL", "SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL");
        new a5(0, "WEB_MESSAGE_PORT_POST_MESSAGE", "WEB_MESSAGE_PORT_POST_MESSAGE");
        new a5(0, "WEB_MESSAGE_PORT_CLOSE", "WEB_MESSAGE_PORT_CLOSE");
        a = new a5(2, "WEB_MESSAGE_ARRAY_BUFFER", "WEB_MESSAGE_ARRAY_BUFFER");
        new a5(0, "WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK", "WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK");
        new a5(0, "CREATE_WEB_MESSAGE_CHANNEL", "CREATE_WEB_MESSAGE_CHANNEL");
        new a5(0, "POST_WEB_MESSAGE", "POST_WEB_MESSAGE");
        new a5(0, "WEB_MESSAGE_CALLBACK_ON_MESSAGE", "WEB_MESSAGE_CALLBACK_ON_MESSAGE");
        new a5(3, "GET_WEB_VIEW_CLIENT", "GET_WEB_VIEW_CLIENT");
        new a5(3, "GET_WEB_CHROME_CLIENT", "GET_WEB_CHROME_CLIENT");
        new a5(6, "GET_WEB_VIEW_RENDERER", "GET_WEB_VIEW_RENDERER");
        new a5(6, "WEB_VIEW_RENDERER_TERMINATE", "WEB_VIEW_RENDERER_TERMINATE");
        new a5(5, "TRACING_CONTROLLER_BASIC_USAGE", "TRACING_CONTROLLER_BASIC_USAGE");
        new xx0();
        new xx0();
        new a5(6, "WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE", "WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE");
        new d81();
        new a5(2, "PROXY_OVERRIDE", "PROXY_OVERRIDE:3");
        b = new a5(2, "MULTI_PROCESS", "MULTI_PROCESS_QUERY");
        new a5(6, "FORCE_DARK", "FORCE_DARK");
        new a5(2, "FORCE_DARK_STRATEGY", "FORCE_DARK_BEHAVIOR");
        c = new a5(2, "WEB_MESSAGE_LISTENER", "WEB_MESSAGE_LISTENER");
        d = new a5(2, "DOCUMENT_START_SCRIPT", "DOCUMENT_START_SCRIPT:1");
        new a5(2, "PROXY_OVERRIDE_REVERSE_BYPASS", "PROXY_OVERRIDE_REVERSE_BYPASS");
        e = new a5(2, "GET_VARIATIONS_HEADER", "GET_VARIATIONS_HEADER");
        new a5(2, "ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY", "ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY");
        new a5(2, "GET_COOKIE_INFO", "GET_COOKIE_INFO");
        new a5(2, "REQUESTED_WITH_HEADER_ALLOW_LIST", "REQUESTED_WITH_HEADER_ALLOW_LIST");
        new a5(2, "USER_AGENT_METADATA", "USER_AGENT_METADATA");
        f = new e81(2, "MULTI_PROFILE", "MULTI_PROFILE");
        new a5(2, "ATTRIBUTION_REGISTRATION_BEHAVIOR", "ATTRIBUTION_BEHAVIOR");
        new a5(2, "WEBVIEW_MEDIA_INTEGRITY_API_STATUS", "WEBVIEW_INTEGRITY_API_STATUS");
        g = new a5(2, "MUTE_AUDIO", "MUTE_AUDIO");
        new a5(2, "WEB_AUTHENTICATION", "WEB_AUTHENTICATION");
        new a5(2, "SPECULATIVE_LOADING_STATUS", "SPECULATIVE_LOADING");
        new a5(2, "BACK_FORWARD_CACHE", "BACK_FORWARD_CACHE");
    }

    public static UnsupportedOperationException a() {
        return new UnsupportedOperationException("This method is not supported by the current version of the framework and the current WebView APK");
    }
}
