package defpackage;

import android.view.ViewGroup;
import java.util.Arrays;
import java.util.HashMap;

/* compiled from: r8-map-id-6c2465e8d13ff8e5d50a476d17d9ba5832a97d3f7cd313d64bb1ddbb52494e1b */
/* loaded from: classes.dex */
public final class ii {
    public int a;
    public final li b;
    public final ki c;
    public final ji d;
    public final mi e;
    public HashMap f;

    public ii() {
        li liVar = new li();
        liVar.a = 0;
        liVar.b = 0;
        liVar.c = 1.0f;
        liVar.d = Float.NaN;
        this.b = liVar;
        ki kiVar = new ki();
        kiVar.a = -1;
        kiVar.b = 0;
        kiVar.c = -1;
        kiVar.d = Float.NaN;
        kiVar.e = Float.NaN;
        kiVar.f = Float.NaN;
        kiVar.g = -1;
        kiVar.h = null;
        kiVar.i = -1;
        this.c = kiVar;
        ji jiVar = new ji();
        jiVar.a = false;
        jiVar.d = -1;
        jiVar.e = -1;
        jiVar.f = -1.0f;
        jiVar.g = true;
        jiVar.h = -1;
        jiVar.i = -1;
        jiVar.j = -1;
        jiVar.k = -1;
        jiVar.l = -1;
        jiVar.m = -1;
        jiVar.n = -1;
        jiVar.o = -1;
        jiVar.p = -1;
        jiVar.q = -1;
        jiVar.r = -1;
        jiVar.s = -1;
        jiVar.t = -1;
        jiVar.u = -1;
        jiVar.v = -1;
        jiVar.w = 0.5f;
        jiVar.x = 0.5f;
        jiVar.y = null;
        jiVar.z = -1;
        jiVar.A = 0;
        jiVar.B = 0.0f;
        jiVar.C = -1;
        jiVar.D = -1;
        jiVar.E = -1;
        jiVar.F = 0;
        jiVar.G = 0;
        jiVar.H = 0;
        jiVar.I = 0;
        jiVar.J = 0;
        jiVar.K = 0;
        jiVar.L = 0;
        jiVar.M = Integer.MIN_VALUE;
        jiVar.N = Integer.MIN_VALUE;
        jiVar.O = Integer.MIN_VALUE;
        jiVar.P = Integer.MIN_VALUE;
        jiVar.Q = Integer.MIN_VALUE;
        jiVar.R = Integer.MIN_VALUE;
        jiVar.S = Integer.MIN_VALUE;
        jiVar.T = -1.0f;
        jiVar.U = -1.0f;
        jiVar.V = 0;
        jiVar.W = 0;
        jiVar.X = 0;
        jiVar.Y = 0;
        jiVar.Z = 0;
        jiVar.a0 = 0;
        jiVar.b0 = 0;
        jiVar.c0 = 0;
        jiVar.d0 = 1.0f;
        jiVar.e0 = 1.0f;
        jiVar.f0 = -1;
        jiVar.g0 = 0;
        jiVar.h0 = -1;
        jiVar.l0 = false;
        jiVar.m0 = false;
        jiVar.n0 = true;
        jiVar.o0 = 0;
        this.d = jiVar;
        mi miVar = new mi();
        miVar.a = 0.0f;
        miVar.b = 0.0f;
        miVar.c = 0.0f;
        miVar.d = 1.0f;
        miVar.e = 1.0f;
        miVar.f = Float.NaN;
        miVar.g = Float.NaN;
        miVar.h = -1;
        miVar.i = 0.0f;
        miVar.j = 0.0f;
        miVar.k = 0.0f;
        miVar.l = false;
        miVar.m = 0.0f;
        this.e = miVar;
        this.f = new HashMap();
    }

    public final void a(ci ciVar) {
        ji jiVar = this.d;
        ciVar.e = jiVar.h;
        ciVar.f = jiVar.i;
        ciVar.g = jiVar.j;
        ciVar.h = jiVar.k;
        ciVar.i = jiVar.l;
        ciVar.j = jiVar.m;
        ciVar.k = jiVar.n;
        ciVar.l = jiVar.o;
        ciVar.m = jiVar.p;
        ciVar.n = jiVar.q;
        ciVar.o = jiVar.r;
        ciVar.s = jiVar.s;
        ciVar.t = jiVar.t;
        ciVar.u = jiVar.u;
        ciVar.v = jiVar.v;
        ((ViewGroup.MarginLayoutParams) ciVar).leftMargin = jiVar.F;
        ((ViewGroup.MarginLayoutParams) ciVar).rightMargin = jiVar.G;
        ((ViewGroup.MarginLayoutParams) ciVar).topMargin = jiVar.H;
        ((ViewGroup.MarginLayoutParams) ciVar).bottomMargin = jiVar.I;
        ciVar.A = jiVar.R;
        ciVar.B = jiVar.Q;
        ciVar.x = jiVar.N;
        ciVar.z = jiVar.P;
        ciVar.E = jiVar.w;
        ciVar.F = jiVar.x;
        ciVar.p = jiVar.z;
        ciVar.q = jiVar.A;
        ciVar.r = jiVar.B;
        ciVar.G = jiVar.y;
        ciVar.T = jiVar.C;
        ciVar.U = jiVar.D;
        ciVar.I = jiVar.T;
        ciVar.H = jiVar.U;
        ciVar.K = jiVar.W;
        ciVar.J = jiVar.V;
        ciVar.W = jiVar.l0;
        ciVar.X = jiVar.m0;
        ciVar.L = jiVar.X;
        ciVar.M = jiVar.Y;
        ciVar.P = jiVar.Z;
        ciVar.Q = jiVar.a0;
        ciVar.N = jiVar.b0;
        ciVar.O = jiVar.c0;
        ciVar.R = jiVar.d0;
        ciVar.S = jiVar.e0;
        ciVar.V = jiVar.E;
        ciVar.c = jiVar.f;
        ciVar.a = jiVar.d;
        ciVar.b = jiVar.e;
        ((ViewGroup.MarginLayoutParams) ciVar).width = jiVar.b;
        ((ViewGroup.MarginLayoutParams) ciVar).height = jiVar.c;
        String str = jiVar.k0;
        if (str != null) {
            ciVar.Y = str;
        }
        ciVar.Z = jiVar.o0;
        ciVar.setMarginStart(jiVar.K);
        ciVar.setMarginEnd(jiVar.J);
        ciVar.a();
    }

    public final Object clone() {
        ii iiVar = new ii();
        ji jiVar = iiVar.d;
        jiVar.getClass();
        ji jiVar2 = this.d;
        jiVar.a = jiVar2.a;
        jiVar.b = jiVar2.b;
        jiVar.c = jiVar2.c;
        jiVar.d = jiVar2.d;
        jiVar.e = jiVar2.e;
        jiVar.f = jiVar2.f;
        jiVar.g = jiVar2.g;
        jiVar.h = jiVar2.h;
        jiVar.i = jiVar2.i;
        jiVar.j = jiVar2.j;
        jiVar.k = jiVar2.k;
        jiVar.l = jiVar2.l;
        jiVar.m = jiVar2.m;
        jiVar.n = jiVar2.n;
        jiVar.o = jiVar2.o;
        jiVar.p = jiVar2.p;
        jiVar.q = jiVar2.q;
        jiVar.r = jiVar2.r;
        jiVar.s = jiVar2.s;
        jiVar.t = jiVar2.t;
        jiVar.u = jiVar2.u;
        jiVar.v = jiVar2.v;
        jiVar.w = jiVar2.w;
        jiVar.x = jiVar2.x;
        jiVar.y = jiVar2.y;
        jiVar.z = jiVar2.z;
        jiVar.A = jiVar2.A;
        jiVar.B = jiVar2.B;
        jiVar.C = jiVar2.C;
        jiVar.D = jiVar2.D;
        jiVar.E = jiVar2.E;
        jiVar.F = jiVar2.F;
        jiVar.G = jiVar2.G;
        jiVar.H = jiVar2.H;
        jiVar.I = jiVar2.I;
        jiVar.J = jiVar2.J;
        jiVar.K = jiVar2.K;
        jiVar.L = jiVar2.L;
        jiVar.M = jiVar2.M;
        jiVar.N = jiVar2.N;
        jiVar.O = jiVar2.O;
        jiVar.P = jiVar2.P;
        jiVar.Q = jiVar2.Q;
        jiVar.R = jiVar2.R;
        jiVar.S = jiVar2.S;
        jiVar.T = jiVar2.T;
        jiVar.U = jiVar2.U;
        jiVar.V = jiVar2.V;
        jiVar.W = jiVar2.W;
        jiVar.X = jiVar2.X;
        jiVar.Y = jiVar2.Y;
        jiVar.Z = jiVar2.Z;
        jiVar.a0 = jiVar2.a0;
        jiVar.b0 = jiVar2.b0;
        jiVar.c0 = jiVar2.c0;
        jiVar.d0 = jiVar2.d0;
        jiVar.e0 = jiVar2.e0;
        jiVar.f0 = jiVar2.f0;
        jiVar.g0 = jiVar2.g0;
        jiVar.h0 = jiVar2.h0;
        jiVar.k0 = jiVar2.k0;
        int[] iArr = jiVar2.i0;
        if (iArr == null || jiVar2.j0 != null) {
            jiVar.i0 = null;
        } else {
            jiVar.i0 = Arrays.copyOf(iArr, iArr.length);
        }
        jiVar.j0 = jiVar2.j0;
        jiVar.l0 = jiVar2.l0;
        jiVar.m0 = jiVar2.m0;
        jiVar.n0 = jiVar2.n0;
        jiVar.o0 = jiVar2.o0;
        ki kiVar = iiVar.c;
        kiVar.getClass();
        ki kiVar2 = this.c;
        kiVar2.getClass();
        kiVar.a = kiVar2.a;
        kiVar.c = kiVar2.c;
        kiVar.e = kiVar2.e;
        kiVar.d = kiVar2.d;
        li liVar = this.b;
        int i = liVar.a;
        li liVar2 = iiVar.b;
        liVar2.a = i;
        liVar2.c = liVar.c;
        liVar2.d = liVar.d;
        liVar2.b = liVar.b;
        mi miVar = iiVar.e;
        miVar.getClass();
        mi miVar2 = this.e;
        miVar2.getClass();
        miVar.a = miVar2.a;
        miVar.b = miVar2.b;
        miVar.c = miVar2.c;
        miVar.d = miVar2.d;
        miVar.e = miVar2.e;
        miVar.f = miVar2.f;
        miVar.g = miVar2.g;
        miVar.h = miVar2.h;
        miVar.i = miVar2.i;
        miVar.j = miVar2.j;
        miVar.k = miVar2.k;
        miVar.l = miVar2.l;
        miVar.m = miVar2.m;
        iiVar.a = this.a;
        return iiVar;
    }
}
