package com.bytedance.sdk.openadsdk.cf;

import android.content.Context;
import android.graphics.Color;
import android.graphics.drawable.Drawable;
import android.text.TextUtils;
import android.util.AttributeSet;
import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.SeekBar;
import com.bytedance.sdk.component.utils.rie;
import com.bytedance.sdk.openadsdk.core.ycc.msw;
import com.bytedance.sdk.openadsdk.core.ycc.uym;
import com.bytedance.sdk.openadsdk.core.ycc.ycc;
import com.bytedance.sdk.openadsdk.utils.gbl;
import com.bytedance.sdk.openadsdk.utils.vk;
import com.bytedance.sdk.openadsdk.utils.vw;

/* loaded from: classes.dex */
public class xq extends uym {
    public xq(Context context) {
        this(context, null);
    }

    private void emc(Context context) {
        setId(520093726);
        setBackgroundColor(-1);
        uym uymVar = new uym(context);
        uymVar.setId(vk.gyw);
        uymVar.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        uymVar.setBackgroundColor(0);
        uymVar.setGravity(17);
        addView(uymVar);
        View dgVar = new com.bytedance.sdk.openadsdk.core.ycc.dg(context);
        dgVar.setId(vk.qp);
        dgVar.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        uymVar.addView(dgVar);
        ycc yccVar = new ycc(context);
        yccVar.setId(vk.iat);
        int iYpw = vw.ypw(context, 60.0f);
        RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(iYpw, iYpw);
        layoutParams.addRule(13);
        yccVar.setLayoutParams(layoutParams);
        yccVar.setIndeterminateDrawable(gbl.emc(context, "tt_video_loading_progress_bar"));
        uymVar.addView(yccVar);
        com.bytedance.sdk.openadsdk.core.ycc.bw bwVar = new com.bytedance.sdk.openadsdk.core.ycc.bw(context);
        bwVar.setId(vk.igv);
        RelativeLayout.LayoutParams layoutParams2 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams2.addRule(13);
        bwVar.setLayoutParams(layoutParams2);
        bwVar.setGravity(1);
        bwVar.setOrientation(1);
        bwVar.setVisibility(8);
        uymVar.addView(bwVar);
        com.bytedance.sdk.openadsdk.core.ycc.dg dgVar2 = new com.bytedance.sdk.openadsdk.core.ycc.dg(context);
        dgVar2.setId(vk.sx);
        dgVar2.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        dgVar2.setImageDrawable(gbl.emc(context, "tt_refreshing_video_textpage"));
        ImageView.ScaleType scaleType = ImageView.ScaleType.CENTER;
        dgVar2.setScaleType(scaleType);
        bwVar.addView(dgVar2);
        msw mswVar = new msw(context);
        mswVar.setId(vk.oz);
        mswVar.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        mswVar.setText(rie.emc(context, "tt_video_retry_des_txt"));
        mswVar.setTextColor(Color.parseColor("#999999"));
        bwVar.addView(mswVar);
        com.bytedance.sdk.openadsdk.core.ycc.dg dgVar3 = new com.bytedance.sdk.openadsdk.core.ycc.dg(context);
        dgVar3.setId(vk.hs);
        RelativeLayout.LayoutParams layoutParams3 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams3.addRule(13);
        dgVar3.setLayoutParams(layoutParams3);
        dgVar3.setScaleType(scaleType);
        dgVar3.setImageDrawable(gbl.emc(context, "tt_play_movebar_textpage"));
        dgVar3.setVisibility(8);
        addView(dgVar3);
        com.bytedance.sdk.openadsdk.core.ycc.dg dgVar4 = new com.bytedance.sdk.openadsdk.core.ycc.dg(context);
        dgVar4.setId(vk.av);
        int iYpw2 = vw.ypw(context, 30.0f);
        RelativeLayout.LayoutParams layoutParams4 = new RelativeLayout.LayoutParams(iYpw2, iYpw2);
        layoutParams4.addRule(21);
        layoutParams4.addRule(11);
        int iYpw3 = vw.ypw(context, 7.0f);
        layoutParams4.setMarginEnd(iYpw3);
        layoutParams4.rightMargin = iYpw3;
        layoutParams4.topMargin = iYpw3;
        dgVar4.setLayoutParams(layoutParams4);
        dgVar4.setBackground(gbl.emc(context, "tt_detail_video_btn_bg"));
        dgVar4.setScaleType(scaleType);
        dgVar4.setImageDrawable(gbl.emc(context, "tt_close_move_detail"));
        addView(dgVar4);
        msw mswVar2 = new msw(context);
        mswVar2.setId(vk.oug);
        RelativeLayout.LayoutParams layoutParams5 = new RelativeLayout.LayoutParams(-1, -2);
        layoutParams5.addRule(9);
        layoutParams5.addRule(20);
        layoutParams5.addRule(10);
        mswVar2.setLayoutParams(layoutParams5);
        mswVar2.setBackground(gbl.emc(context, "tt_video_black_desc_gradient"));
        TextUtils.TruncateAt truncateAt = TextUtils.TruncateAt.END;
        mswVar2.setEllipsize(truncateAt);
        mswVar2.setMaxLines(2);
        int iYpw4 = vw.ypw(context, 15.0f);
        mswVar2.setPadding(iYpw4, vw.ypw(context, 14.0f), iYpw4, 0);
        mswVar2.setSingleLine(false);
        mswVar2.setTextColor(-1);
        mswVar2.setTextSize(2, 17.0f);
        mswVar2.setVisibility(8);
        addView(mswVar2);
        uym uymVar2 = new uym(context);
        uymVar2.setId(vk.fxt);
        RelativeLayout.LayoutParams layoutParams6 = new RelativeLayout.LayoutParams(-1, -2);
        layoutParams6.addRule(10);
        uymVar2.setLayoutParams(layoutParams6);
        uymVar2.setBackground(gbl.emc(context, "tt_video_black_desc_gradient"));
        uymVar2.setGravity(16);
        uymVar2.setVisibility(8);
        addView(uymVar2);
        com.bytedance.sdk.openadsdk.core.ycc.dg dgVar5 = new com.bytedance.sdk.openadsdk.core.ycc.dg(context);
        int i = vk.knr;
        dgVar5.setId(i);
        RelativeLayout.LayoutParams layoutParams7 = new RelativeLayout.LayoutParams(-2, -1);
        layoutParams7.addRule(15);
        int iYpw5 = vw.ypw(context, 12.0f);
        layoutParams7.leftMargin = iYpw5;
        layoutParams7.setMarginStart(iYpw5);
        dgVar5.setLayoutParams(layoutParams7);
        dgVar5.setScaleType(scaleType);
        dgVar5.setImageDrawable(gbl.emc(context, "tt_leftbackbutton_titlebar_photo_preview"));
        uymVar2.addView(dgVar5);
        msw mswVar3 = new msw(context);
        mswVar3.setId(vk.ya);
        RelativeLayout.LayoutParams layoutParams8 = new RelativeLayout.LayoutParams(-2, -1);
        layoutParams8.addRule(15);
        int iYpw6 = vw.ypw(context, 16.0f);
        layoutParams8.leftMargin = iYpw6;
        layoutParams8.rightMargin = iYpw;
        layoutParams8.setMarginStart(iYpw6);
        layoutParams8.setMarginEnd(iYpw);
        layoutParams8.addRule(17, i);
        int i3 = vk.tc;
        layoutParams8.addRule(0, i3);
        layoutParams8.addRule(1, i);
        layoutParams8.addRule(16, i3);
        mswVar3.setLayoutParams(layoutParams8);
        mswVar3.setEllipsize(truncateAt);
        mswVar3.setGravity(16);
        mswVar3.setMaxLines(1);
        mswVar3.setSingleLine(true);
        mswVar3.setTextColor(-1);
        mswVar3.setTextSize(2, 17.0f);
        uymVar2.addView(mswVar3);
        com.bytedance.sdk.openadsdk.core.ycc.bw bwVar2 = new com.bytedance.sdk.openadsdk.core.ycc.bw(context);
        bwVar2.setId(i3);
        RelativeLayout.LayoutParams layoutParams9 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams9.addRule(21);
        layoutParams9.addRule(11);
        int iYpw7 = vw.ypw(context, 14.0f);
        layoutParams9.rightMargin = iYpw7;
        layoutParams9.setMarginEnd(iYpw7);
        bwVar2.setLayoutParams(layoutParams9);
        bwVar2.setGravity(16);
        bwVar2.setOrientation(1);
        uymVar2.addView(bwVar2);
        msw mswVar4 = new msw(context);
        mswVar4.setId(vk.xst);
        LinearLayout.LayoutParams layoutParams10 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams10.gravity = 1;
        mswVar4.setLayoutParams(layoutParams10);
        mswVar4.setGravity(16);
        mswVar4.setMaxLines(1);
        mswVar4.setSingleLine(true);
        mswVar4.setTextColor(-1);
        mswVar4.setTextSize(2, 12.0f);
        bwVar2.addView(mswVar4);
        com.bytedance.sdk.openadsdk.core.ycc.bw bwVar3 = new com.bytedance.sdk.openadsdk.core.ycc.bw(context);
        bwVar3.setId(vk.rr);
        RelativeLayout.LayoutParams layoutParams11 = new RelativeLayout.LayoutParams(-2, vw.ypw(context, 40.0f));
        layoutParams11.addRule(12);
        layoutParams11.addRule(21);
        layoutParams11.addRule(11);
        bwVar3.setLayoutParams(layoutParams11);
        bwVar3.setGravity(16);
        bwVar3.setOrientation(0);
        bwVar3.setVisibility(8);
        addView(bwVar3);
        msw mswVar5 = new msw(context);
        mswVar5.setId(vk.dm);
        LinearLayout.LayoutParams layoutParams12 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams12.leftMargin = iYpw6;
        layoutParams12.rightMargin = iYpw5;
        layoutParams12.setMarginEnd(iYpw5);
        layoutParams12.setMarginStart(iYpw6);
        mswVar5.setLayoutParams(layoutParams12);
        mswVar5.setText(rie.emc(context, "tt_00_00"));
        mswVar5.setTextColor(-1);
        mswVar5.setTextSize(2, 10.0f);
        bwVar3.addView(mswVar5);
        SeekBar seekBar = new SeekBar(context);
        seekBar.setId(vk.cwv);
        LinearLayout.LayoutParams layoutParams13 = new LinearLayout.LayoutParams(0, vw.ypw(context, 5.0f));
        layoutParams13.gravity = 16;
        seekBar.setLayoutParams(layoutParams13);
        seekBar.setMax(100);
        seekBar.setPadding(0, 0, 0, 0);
        seekBar.setProgressDrawable(gbl.emc(context, "tt_seek_progress"));
        seekBar.setThumb(gbl.emc(context, "tt_seek_thumb"));
        seekBar.setThumbOffset(0);
        bwVar3.addView(seekBar);
        msw mswVar6 = new msw(context);
        mswVar6.setId(vk.ff);
        LinearLayout.LayoutParams layoutParams14 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams14.leftMargin = iYpw5;
        layoutParams14.rightMargin = iYpw6;
        layoutParams14.setMarginEnd(iYpw6);
        layoutParams14.setMarginStart(iYpw5);
        mswVar6.setLayoutParams(layoutParams14);
        mswVar6.setText(rie.emc(context, "tt_00_00"));
        mswVar6.setTextColor(-1);
        mswVar6.setTextSize(2, 10.0f);
        bwVar3.addView(mswVar6);
        com.bytedance.sdk.openadsdk.core.ycc.dg dgVar6 = new com.bytedance.sdk.openadsdk.core.ycc.dg(context);
        dgVar6.setId(vk.wq);
        dgVar6.setLayoutParams(new LinearLayout.LayoutParams(-2, -1));
        dgVar6.setPadding(iYpw6, 0, iYpw6, 0);
        dgVar6.setScaleType(scaleType);
        dgVar6.setVisibility(8);
        dgVar6.setImageDrawable(rie.xq(context, "tt_enlarge_video"));
        bwVar3.addView(dgVar6);
        View ypwVar = new ypw(context);
        ypwVar.setId(vk.sg);
        ypwVar.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        addView(ypwVar);
        msw mswVar7 = new msw(context);
        mswVar7.setId(vk.xou);
        RelativeLayout.LayoutParams layoutParams15 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams15.leftMargin = iYpw5;
        layoutParams15.addRule(9);
        layoutParams15.addRule(20);
        mswVar7.setLayoutParams(layoutParams15);
        mswVar7.setBackgroundColor(Color.parseColor("#00000000"));
        mswVar7.setText("close");
        mswVar7.setMinHeight(vw.ypw(context, 44.0f));
        mswVar7.setCompoundDrawablesWithIntrinsicBounds(gbl.emc(context, "tt_shadow_btn_back"), (Drawable) null, (Drawable) null, (Drawable) null);
        addView(mswVar7);
    }

    public xq(Context context, AttributeSet attributeSet) {
        this(context, attributeSet, 0);
    }

    public xq(Context context, AttributeSet attributeSet, int i) {
        super(context, attributeSet, i);
        emc(context);
    }
}
